backend:
  name: git-gateway
  branch: master

media_folder: "static/img/uploads"
public_folder: "img/uploads"

collections: 
  - name: "myJulySite"
    label: "July Site"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string", required: true}
      